const express = require('express')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const cors = require('cors')
const app = express()
const BlogsP = require('./routes/blog')
app.use(cors())
app.use(express.json())
app.use(bodyParser.json())
app.get('/',()=>{
    console.log('Working')
})
app.use('/api/blogs',BlogsP)
app.listen(5000)
mongoose.connect('mongodb+srv://Stakes:A12345678@glabc.unjlu.mongodb.net/PenScales?retryWrites=true&w=majority',()=>{
  console.log('connected to db')
})